# -----------------------------
# Basic Site Info
# -----------------------------
name: Daily Insight
description: "Har din naye insights, coding tips, tech updates aur trending blogs — simplified for readers."
avatar: "https://avatars.githubusercontent.com/u/158843275?s=400&u=70f60a6fa81517d50dbba47b462c3a25abce68a7&v=4"

# -----------------------------
# Footer / Social Links
# -----------------------------
footer-links:
  github: "Chauhan0047"
  twitter: "harshu_ux"
  linkedin: "himanshu-kumar-635a492b9"
  email: "chauhan7668788654@gmail.com"
  rss: "/feed.xml"

# -----------------------------
# Comments / Analytics
# -----------------------------
disqus: ""          # Agar comments chahte ho to apna Disqus shortname daal do
google_analytics: "" # Agar traffic track karna ho to apna GA code daal do

# -----------------------------
# Domain & URL
# -----------------------------
url: "https://www.dailyinsight.me"
baseurl: ""        # project repo ke liye "/repo-name", user site ke liye empty
permalink: /:title/

# -----------------------------
# Markdown / Syntax Highlighting
# -----------------------------
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# -----------------------------
# Styling
# -----------------------------
sass:
  style: :expanded

# -----------------------------
# Plugins
# -----------------------------
gems:
  - jekyll-sitemap   # Automatic sitemap.xml (SEO ke liye)
  - jekyll-feed      # RSS feed (traffic aur subscribers ke liye)

# -----------------------------
# Exclude unnecessary files
# -----------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

